[package]
name = "dcd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zip = "0.6.3"
rustyline = "10.0.0"
env_logger = "0.9.3"
log = "0.4.17"
bitflags = "1.3.2"
